"""
Seed real internships, clubs, and communities into the production database.
Run: DATABASE_URL="..." python3 seed_data.py
"""
import os, sys
os.environ.setdefault("DATABASE_URL", "sqlite:///icon.db")

from app import create_app, db
from models import Job, Club

app = create_app()

JOBS = [
    {
        "title": "Software Engineer Intern",
        "company": "Samsung Electronics",
        "location": "Suwon, South Korea",
        "job_type": "Internship",
        "salary": "₩2,500,000/month",
        "description": "Join Samsung's world-class software engineering team. Work on cutting-edge embedded systems, AI platforms, or mobile software. You will collaborate with senior engineers on real product features shipped to millions of users worldwide.",
        "requirements": "Currently enrolled in CS, Software Engineering, or related field\nProficiency in C++, Java, or Python\nBasic understanding of data structures and algorithms\nEnglish or Korean communication skills",
        "visa_compatible": "D-2, D-10",
        "deadline": "2025-08-31",
        "tags": "Software, AI, Mobile, Embedded",
        "apply_link": "https://sec.wd3.myworkdayjobs.com/en-US/Samsung_Careers",
    },
    {
        "title": "AI/ML Research Intern",
        "company": "LG Electronics",
        "location": "Seoul, South Korea",
        "job_type": "Internship",
        "salary": "₩2,200,000/month",
        "description": "Work alongside LG's AI research lab on computer vision, NLP, and smart home AI systems. Contribute to publishable research and real product integrations across LG ThinQ ecosystem.",
        "requirements": "Background in Machine Learning or Computer Science\nExperience with PyTorch or TensorFlow\nFamiliarity with research papers and implementation\nEnglish proficiency required",
        "visa_compatible": "D-2, D-10",
        "deadline": "2025-07-31",
        "tags": "AI, Machine Learning, Research, Computer Vision",
        "apply_link": "https://www.linkedin.com/jobs/search/?keywords=LG+Electronics+intern+Korea",
    },
    {
        "title": "Backend Developer Intern",
        "company": "Kakao",
        "location": "Pangyo, South Korea",
        "job_type": "Internship",
        "salary": "₩2,800,000/month",
        "description": "Build and optimize backend services powering KakaoTalk, KakaoPay, and KakaoMap used by 50M+ users. Work with Go, Java Spring, and distributed systems at massive scale.",
        "requirements": "Strong knowledge of Java, Go, or Python\nFamiliarity with REST APIs and microservices\nBasic knowledge of SQL and NoSQL databases\nIntermediate Korean or English skills",
        "visa_compatible": "D-2, D-10",
        "deadline": "2025-09-15",
        "tags": "Backend, Java, Go, Microservices",
        "apply_link": "https://careers.kakao.com/jobs?lang=en",
    },
    {
        "title": "Frontend Engineer Intern",
        "company": "Naver",
        "location": "Seongnam, South Korea",
        "job_type": "Internship",
        "salary": "₩2,600,000/month",
        "description": "Develop user interfaces for Naver Search, Naver Blog, and LINE services used across Asia. You'll work with React, TypeScript, and Naver's design system to build fast, accessible web experiences.",
        "requirements": "Proficiency in React or Vue.js\nKnowledge of HTML, CSS, TypeScript\nPortfolio of web projects preferred\nBasic Korean reading ability",
        "visa_compatible": "D-2, D-10",
        "deadline": "2025-08-15",
        "tags": "Frontend, React, TypeScript, UX",
        "apply_link": "https://naver-career.gitbook.io/en",
    },
    {
        "title": "Semiconductor Process Engineering Intern",
        "company": "SK Hynix",
        "location": "Icheon, South Korea",
        "job_type": "Internship",
        "salary": "₩2,400,000/month",
        "description": "Assist in DRAM and NAND flash memory process development at one of the world's largest semiconductor manufacturers. Gain hands-on experience in cleanroom operations, yield analysis, and process optimization.",
        "requirements": "Major in Electrical Engineering, Materials Science, or Physics\nBasic understanding of semiconductor fabrication\nAnalytical and problem-solving skills\nKorean preferred but not required",
        "visa_compatible": "D-2, D-10",
        "deadline": "2025-10-01",
        "tags": "Semiconductor, Hardware, Engineering, DRAM",
        "apply_link": "https://www.skhynix.com/eng/careers/jobOpportunities.do",
    },
    {
        "title": "Autonomous Vehicle Software Intern",
        "company": "Hyundai Motor Company",
        "location": "Seoul, South Korea",
        "job_type": "Internship",
        "salary": "₩2,500,000/month",
        "description": "Join Hyundai's future mobility team working on self-driving car software, sensor fusion, and ADAS systems. Collaborate with engineers on perception algorithms and simulation testing.",
        "requirements": "Background in Computer Science, Robotics, or Electrical Engineering\nC++ and Python programming skills\nKnowledge of ROS or autonomous systems a plus\nEnglish communication required",
        "visa_compatible": "D-2, D-10",
        "deadline": "2025-09-30",
        "tags": "Autonomous, AI, Robotics, Automotive",
        "apply_link": "https://www.hyundai.com/worldwide/en/company/careers",
    },
    {
        "title": "Game Developer Intern",
        "company": "Krafton (PUBG Studios)",
        "location": "Seoul, South Korea",
        "job_type": "Internship",
        "salary": "₩2,700,000/month",
        "description": "Work on PUBG: BATTLEGROUNDS or new game projects at one of Korea's top gaming companies. Contribute to gameplay mechanics, server optimization, or tools development used by 75M+ players.",
        "requirements": "Experience with Unreal Engine or Unity\nC++ or C# programming skills\nPassion for gaming and game development\nPortfolio of game projects required",
        "visa_compatible": "D-2, D-10",
        "deadline": "2025-08-31",
        "tags": "Game Dev, Unreal Engine, C++, Gaming",
        "apply_link": "https://krafton.com/en/careers/",
    },
    {
        "title": "Data Science Intern",
        "company": "Coupang",
        "location": "Seoul, South Korea",
        "job_type": "Internship",
        "salary": "₩3,000,000/month",
        "description": "Apply machine learning and data analysis to improve Coupang's logistics, recommendation systems, and pricing engine. Work with petabyte-scale data and deploy models that affect millions of daily transactions.",
        "requirements": "Strong Python skills (pandas, scikit-learn, PyTorch)\nExperience with SQL and big data tools (Spark, Hive)\nBackground in Statistics or Computer Science\nEnglish fluency required",
        "visa_compatible": "D-2, D-10",
        "deadline": "2025-07-31",
        "tags": "Data Science, ML, Python, E-commerce",
        "apply_link": "https://www.coupang.jobs/en/jobs/",
    },
    {
        "title": "LINE Mobile App Intern",
        "company": "LY Corporation (LINE)",
        "location": "Seoul, South Korea",
        "job_type": "Internship",
        "salary": "₩2,500,000/month",
        "description": "Develop features for LINE messenger used by 200M+ users across Asia. Work on iOS or Android native development, contributing to chat, payments, and mini-app features.",
        "requirements": "Swift/Kotlin or React Native experience\nUnderstanding of mobile app architecture\nGit workflow knowledge\nEnglish or Japanese communication skills",
        "visa_compatible": "D-2, D-10",
        "deadline": "2025-08-20",
        "tags": "Mobile, iOS, Android, Messaging",
        "apply_link": "https://careers.linecorp.com/en/",
    },
    {
        "title": "Delivery App Product Intern",
        "company": "Woowa Brothers (Baemin)",
        "location": "Seoul, South Korea",
        "job_type": "Internship",
        "salary": "₩2,300,000/month",
        "description": "Work on Korea's #1 food delivery app used by 30M+ users. Join the product team to analyze user behavior, run A/B tests, define features, and collaborate with designers and engineers on Baemin's growth.",
        "requirements": "Interest in product management and UX\nData analysis skills (SQL, Excel)\nStrong communication and presentation skills\nIntermediate Korean preferred",
        "visa_compatible": "D-2, D-10",
        "deadline": "2025-09-01",
        "tags": "Product, UX, Growth, Food Tech",
        "apply_link": "https://career.woowahan.com/",
    },
    {
        "title": "Cloud Infrastructure Intern",
        "company": "SK Telecom",
        "location": "Seoul, South Korea",
        "job_type": "Internship",
        "salary": "₩2,400,000/month",
        "description": "Work on SK Telecom's cloud and 5G infrastructure, supporting AI services, edge computing, and network automation. Gain exposure to telecom-grade distributed systems and cloud-native deployments.",
        "requirements": "Background in Computer Science or Network Engineering\nFamiliarity with AWS, GCP, or Azure\nLinux and scripting knowledge\nKorean communication skills preferred",
        "visa_compatible": "D-2, D-10",
        "deadline": "2025-10-15",
        "tags": "Cloud, 5G, DevOps, Infrastructure",
        "apply_link": "https://www.linkedin.com/jobs/search/?keywords=SK+Telecom+intern",
    },
    {
        "title": "Research Intern – Materials Science",
        "company": "POSCO",
        "location": "Pohang, South Korea",
        "job_type": "Internship",
        "salary": "₩2,000,000/month",
        "description": "Join POSCO's R&D center to research advanced steel and next-generation battery materials. Work alongside PhD researchers on projects for the EV and energy storage industries.",
        "requirements": "Major in Materials Science, Chemistry, or Metallurgy\nLab research experience preferred\nReport writing skills in English or Korean\nWillingness to relocate to Pohang",
        "visa_compatible": "D-2, D-10",
        "deadline": "2025-08-01",
        "tags": "Materials, Research, Battery, Steel",
        "apply_link": "https://www.linkedin.com/jobs/search/?keywords=POSCO+intern+Korea",
    },
    {
        "title": "Game Designer Intern",
        "company": "NCSoft",
        "location": "Seongnam, South Korea",
        "job_type": "Internship",
        "salary": "₩2,300,000/month",
        "description": "Contribute to game design for Lineage, Blade & Soul, or new MMORPG projects at NCSoft. Design quests, balance game economies, create system specs, and collaborate with art and engineering teams.",
        "requirements": "Portfolio of game design work (mods, game jam projects)\nPassion for RPG and online gaming\nDocumentation and analytical skills\nBasic Korean helpful",
        "visa_compatible": "D-2, D-10",
        "deadline": "2025-09-15",
        "tags": "Game Design, RPG, MMORPG, Creative",
        "apply_link": "https://www.linkedin.com/jobs/search/?keywords=NCSoft+intern",
    },
    {
        "title": "Trade & Business Intern",
        "company": "KOTRA (Korea Trade-Investment Promotion Agency)",
        "location": "Seoul, South Korea",
        "job_type": "Internship",
        "salary": "₩1,800,000/month",
        "description": "Support Korea's global trade promotion activities. Research foreign markets, assist companies entering Korean market, prepare reports on international trade trends, and support KOTRA's global network of 127 offices.",
        "requirements": "Business, Economics, or International Relations background\nStrong research and writing skills\nProficiency in English plus one other language\nInterest in international trade and Korea",
        "visa_compatible": "D-2, D-10, F-2",
        "deadline": "2025-07-15",
        "tags": "Trade, Business, International, Government",
        "apply_link": "https://www.kotra.or.kr/kh/about/KHAHAK010M.do",
    },
    {
        "title": "Digital Marketing Intern",
        "company": "Korea Tourism Organization (KTO)",
        "location": "Seoul, South Korea",
        "job_type": "Internship",
        "salary": "₩1,700,000/month",
        "description": "Create content and run digital campaigns promoting Korean tourism globally. Manage social media accounts, analyze campaign data, produce multilingual content, and support international tourism fairs.",
        "requirements": "Marketing, Communications, or Media background\nSocial media management experience\nContent creation skills (writing, photography, video)\nFluency in English, and ideally another language",
        "visa_compatible": "D-2, D-10, F-2",
        "deadline": "2025-08-15",
        "tags": "Marketing, Tourism, Content, Social Media",
        "apply_link": "https://www.linkedin.com/jobs/search/?keywords=Korea+Tourism+Organization+intern",
    },
    {
        "title": "Cybersecurity Research Intern",
        "company": "KISA (Korea Internet & Security Agency)",
        "location": "Seoul, South Korea",
        "job_type": "Internship",
        "salary": "₩2,000,000/month",
        "description": "Research cybersecurity threats, assist with vulnerability analysis, and support Korea's national cybersecurity initiatives. Work on malware analysis, incident response, and security policy research.",
        "requirements": "Computer Science or Information Security background\nKnowledge of networking and security fundamentals\nCTF experience or security certifications a plus\nKorean language ability required",
        "visa_compatible": "D-2, D-10",
        "deadline": "2025-09-30",
        "tags": "Cybersecurity, Research, Networking, Security",
        "apply_link": "https://www.kisa.or.kr/20301/form?postSeq=0&lang_type=KO",
    },
    {
        "title": "Fintech Product Intern",
        "company": "Kakao Pay",
        "location": "Seoul, South Korea",
        "job_type": "Internship",
        "salary": "₩2,800,000/month",
        "description": "Work on KakaoPay's digital payments and financial services platform used by 38M users. Help design and test payment flows, insurance products, and investment features for one of Korea's top fintech companies.",
        "requirements": "Interest in fintech and digital payments\nData analysis skills\nUX research or product management interest\nKorean communication skills preferred",
        "visa_compatible": "D-2, D-10",
        "deadline": "2025-08-31",
        "tags": "Fintech, Payments, Product, Finance",
        "apply_link": "https://careers.kakao.com/jobs?lang=en&part=kakaopay",
    },
    {
        "title": "Biotech Research Intern",
        "company": "Samsung Biologics",
        "location": "Incheon, South Korea",
        "job_type": "Internship",
        "salary": "₩2,200,000/month",
        "description": "Support biopharmaceutical manufacturing research and quality control at Samsung Biologics, the world's largest biologics CMO. Work in cell culture, analytical development, or process engineering teams.",
        "requirements": "Major in Biotechnology, Biochemistry, or Chemical Engineering\nLab experience required\nGMP or biologics knowledge a plus\nEnglish communication required",
        "visa_compatible": "D-2, D-10",
        "deadline": "2025-10-31",
        "tags": "Biotech, Pharma, Lab, Research",
        "apply_link": "https://www.linkedin.com/jobs/search/?keywords=Samsung+Biologics+intern",
    },
    {
        "title": "UI/UX Design Intern",
        "company": "Krafton (PUBG Studios)",
        "location": "Seoul, South Korea",
        "job_type": "Internship",
        "salary": "₩2,300,000/month",
        "description": "Design intuitive and engaging game UI for PUBG and new titles. Create wireframes, prototypes, and final assets while collaborating closely with game designers and frontend engineers.",
        "requirements": "Portfolio showcasing UI/UX or graphic design work\nProficiency in Figma or Adobe XD\nBasic understanding of game UI/UX principles\nEnglish or Korean communication skills",
        "visa_compatible": "D-2, D-10",
        "deadline": "2025-09-01",
        "tags": "UI/UX, Design, Figma, Gaming",
        "apply_link": "https://krafton.com/en/careers/",
    },
    {
        "title": "Robotics Engineering Intern",
        "company": "Hyundai Robotics",
        "location": "Ulsan, South Korea",
        "job_type": "Internship",
        "salary": "₩2,400,000/month",
        "description": "Work on industrial and service robot development at Hyundai Robotics. Contribute to motion planning, ROS-based control systems, and human-robot interaction projects for manufacturing and logistics robots.",
        "requirements": "Background in Robotics, Mechanical, or Electrical Engineering\nROS and Python or C++ skills\nExperience with robot simulation (Gazebo, MuJoCo)\nEnglish required; Korean a plus",
        "visa_compatible": "D-2, D-10",
        "deadline": "2025-10-15",
        "tags": "Robotics, ROS, Engineering, Automation",
        "apply_link": "https://www.hyundai.com/worldwide/en/company/careers",
    },
]

CLUBS = [
    # ── CLUBS ────────────────────────────────────────────────
    {
        "name": "Korean Language Exchange Club",
        "description": "Practice Korean with native speakers while teaching them your language. Weekly conversation sessions, K-drama watch parties, and cultural exchange events. All levels welcome!",
        "category": "Language",
        "university": "JBNU",
        "club_type": "club",
        "meeting_time": "Every Wednesday 6:00 PM",
        "location": "Student Union Building, Room 201",
        "country": None,
    },
    {
        "name": "International Basketball Club",
        "description": "Competitive and casual basketball for international students. We play 3v3 and 5v5 games every weekend and participate in JBNU inter-club tournaments. All skill levels welcome.",
        "category": "Sports",
        "university": "JBNU",
        "club_type": "club",
        "meeting_time": "Saturday & Sunday 3:00 PM",
        "location": "JBNU Sports Complex, Gym A",
        "country": None,
    },
    {
        "name": "K-Pop Dance Crew",
        "description": "Learn K-pop choreography from BTS, BLACKPINK, aespa, and more. We perform at university festivals and create content for social media. No prior dance experience needed.",
        "category": "Arts & Culture",
        "university": "JBNU",
        "club_type": "club",
        "meeting_time": "Tuesday & Thursday 7:00 PM",
        "location": "Culture Hall Dance Studio",
        "country": None,
    },
    {
        "name": "Hiking & Outdoor Adventures",
        "description": "Explore Korea's beautiful mountains and national parks together. Monthly hikes to destinations like Naejangsan, Deogyusan, and Jirisan. Equipment sharing available for members.",
        "category": "Outdoor",
        "university": "JBNU",
        "club_type": "club",
        "meeting_time": "First Sunday of each month, 7:00 AM",
        "location": "JBNU Main Gate (meetup point)",
        "country": None,
    },
    {
        "name": "International Food Culture Club",
        "description": "Cook and share dishes from around the world! Monthly potluck dinners, cooking workshops, and food market visits. Discover new cuisines while sharing your home country's food traditions.",
        "category": "Food & Culture",
        "university": "JBNU",
        "club_type": "club",
        "meeting_time": "Every other Saturday 5:00 PM",
        "location": "International House Kitchen",
        "country": None,
    },
    {
        "name": "Startup & Entrepreneurship Club",
        "description": "Build your startup idea from scratch. We run weekly pitch sessions, connect you with mentors, visit Korean startups in Pangyo, and help you apply to accelerators like TIPS and K-Startup.",
        "category": "Business",
        "university": "JBNU",
        "club_type": "club",
        "meeting_time": "Every Monday 6:00 PM",
        "location": "Innovation Hub, Room 305",
        "country": None,
    },
    {
        "name": "Photography & Visual Arts Club",
        "description": "Explore Korea through your lens. Weekly photography walks in Jeonju Hanok Village, photo editing workshops, and an annual exhibition of members' best work. Cameras and editing software provided.",
        "category": "Arts & Culture",
        "university": "JBNU",
        "club_type": "club",
        "meeting_time": "Every Friday 4:00 PM",
        "location": "Arts Building, Studio B",
        "country": None,
    },
    {
        "name": "Tech & Coding Club",
        "description": "Learn programming, build projects, compete in hackathons. Weekly workshops on web development, AI, app development, and competitive programming. From beginner to advanced levels.",
        "category": "Technology",
        "university": "JBNU",
        "club_type": "club",
        "meeting_time": "Wednesday & Friday 5:00 PM",
        "location": "Engineering Building, Computer Lab 2",
        "country": None,
    },
    {
        "name": "Debate & Public Speaking Club",
        "description": "Sharpen your critical thinking and English communication skills. We do weekly debates on global issues, Oxford-style rounds, TED-style talk practice, and compete in inter-university tournaments.",
        "category": "Academic",
        "university": "JBNU",
        "club_type": "club",
        "meeting_time": "Every Tuesday 5:30 PM",
        "location": "Liberal Arts Building, Room 102",
        "country": None,
    },
    {
        "name": "Yoga & Wellness Club",
        "description": "De-stress from academic life with yoga, meditation, and mindfulness sessions. Beginner-friendly classes every morning, plus workshops on mental health and wellness strategies for international students.",
        "category": "Health & Wellness",
        "university": "JBNU",
        "club_type": "club",
        "meeting_time": "Monday, Wednesday, Friday 7:30 AM",
        "location": "Student Wellness Center",
        "country": None,
    },
    {
        "name": "Badminton Club",
        "description": "Casual and competitive badminton for all skill levels. We have rackets and shuttlecocks available. Regular inter-university matches and a friendly tournament every semester.",
        "category": "Sports",
        "university": "JBNU",
        "club_type": "club",
        "meeting_time": "Tuesday & Thursday 8:00 PM",
        "location": "Sports Complex, Badminton Courts",
        "country": None,
    },
    {
        "name": "Guitar & Music Club",
        "description": "Play, learn, and perform music together. Weekly jam sessions covering K-pop, pop, folk, and classical. Open mic nights every month. Guitars and basic equipment provided for new members.",
        "category": "Arts & Culture",
        "university": "JBNU",
        "club_type": "club",
        "meeting_time": "Every Thursday 7:00 PM",
        "location": "Culture Hall, Music Room 1",
        "country": None,
    },
    {
        "name": "Volunteer & Community Service Club",
        "description": "Give back to the Jeonju community. We organize tutoring for local children, elderly care visits, environmental clean-ups, and cultural education events. Great for building Korean social networks.",
        "category": "Volunteer",
        "university": "JBNU",
        "club_type": "club",
        "meeting_time": "Every Sunday 10:00 AM",
        "location": "Student Union, Volunteer Center",
        "country": None,
    },
    # ── COMMUNITIES ───────────────────────────────────────────
    {
        "name": "Muslim Students Association",
        "description": "A welcoming community for Muslim students in Jeonju. We organize Friday prayers, halal food guides, Ramadan iftars, Eid celebrations, and support new Muslim students adjusting to life in Korea.",
        "category": "Religion & Culture",
        "university": "JBNU",
        "club_type": "community",
        "meeting_time": "Friday Prayer 1:00 PM, Weekly meetup Sunday 6:00 PM",
        "location": "International House, Common Room",
        "country": None,
    },
    {
        "name": "Vietnamese Students Community",
        "description": "Connect with fellow Vietnamese students across Jeonju universities. Monthly cultural events, Tết celebrations, Vietnamese food gatherings, and peer support network for academic and daily life in Korea.",
        "category": "National Community",
        "university": "JBNU",
        "club_type": "community",
        "meeting_time": "Every other Sunday 4:00 PM",
        "location": "International House, Room 105",
        "country": "Vietnam",
    },
    {
        "name": "Chinese Students & Scholars Association",
        "description": "The largest international student community at JBNU. Supporting Chinese students with arrival guidance, academic resources, Chinese New Year celebrations, and cultural exchange with Korean students.",
        "category": "National Community",
        "university": "JBNU",
        "club_type": "community",
        "meeting_time": "Every Saturday 3:00 PM",
        "location": "International House, Hall A",
        "country": "China",
    },
    {
        "name": "Central Asian Students Community",
        "description": "A home away from home for students from Kazakhstan, Uzbekistan, Kyrgyzstan, Tajikistan, and Turkmenistan. Nowruz celebrations, cultural nights, and peer support for adapting to Korean university life.",
        "category": "National Community",
        "university": "JBNU",
        "club_type": "community",
        "meeting_time": "Every Friday 6:00 PM",
        "location": "International House, Room 203",
        "country": None,
    },
    {
        "name": "African Students Community",
        "description": "Bringing together students from across Africa. Cultural festivals, African cuisine nights, support network for studying in Korea, and building bridges between African and Korean cultures.",
        "category": "National Community",
        "university": "JBNU",
        "club_type": "community",
        "meeting_time": "Every other Saturday 5:00 PM",
        "location": "International House, Room 107",
        "country": None,
    },
    {
        "name": "South & Southeast Asian Community",
        "description": "Community for students from India, Nepal, Bangladesh, Sri Lanka, Thailand, Indonesia, Malaysia, and the Philippines. Diwali, Holi, and diverse cultural celebrations throughout the year.",
        "category": "National Community",
        "university": "JBNU",
        "club_type": "community",
        "meeting_time": "Every Sunday 5:00 PM",
        "location": "International House, Room 204",
        "country": None,
    },
    {
        "name": "LGBTQ+ International Safe Space",
        "description": "A safe and supportive community for LGBTQ+ international students in Korea. Weekly meetups, peer support, navigating life in Korea as an LGBTQ+ person, and social events.",
        "category": "Support & Community",
        "university": "JBNU",
        "club_type": "community",
        "meeting_time": "Every Wednesday 7:00 PM",
        "location": "Student Counseling Center (Room varies)",
        "country": None,
    },
    {
        "name": "International Mentorship Network",
        "description": "Connecting new international students with experienced ones. Get guidance on registration, housing, banking, phone plans, and thriving at JBNU. Senior students mentor freshers through their first semester.",
        "category": "Support & Community",
        "university": "JBNU",
        "club_type": "community",
        "meeting_time": "Orientation events + on-demand",
        "location": "International Student Office",
        "country": None,
    },
    {
        "name": "Christian International Fellowship",
        "description": "A welcoming Christian community for international students. Sunday worship services in English, Bible study, prayer groups, and community outreach activities. All denominations welcome.",
        "category": "Religion & Culture",
        "university": "JBNU",
        "club_type": "community",
        "meeting_time": "Sunday Service 11:00 AM, Bible Study Wednesday 7:00 PM",
        "location": "Campus Chapel",
        "country": None,
    },
    {
        "name": "Russian-Speaking Students Community",
        "description": "Community for Russian-speaking students from Russia, Belarus, Ukraine, and other CIS countries. Russian cultural nights, Victory Day and New Year celebrations, and mutual support network.",
        "category": "National Community",
        "university": "JBNU",
        "club_type": "community",
        "meeting_time": "Every Saturday 4:00 PM",
        "location": "International House, Room 108",
        "country": None,
    },
    {
        "name": "Latin American & Spanish-Speaking Community",
        "description": "¡Hola! A vibrant community for students from Latin America and Spanish-speaking countries. Salsa nights, cultural festivals, Spanish language exchange, and Latin American cuisine events.",
        "category": "National Community",
        "university": "JBNU",
        "club_type": "community",
        "meeting_time": "Every Friday 7:00 PM",
        "location": "International House, Hall B",
        "country": None,
    },
    {
        "name": "Middle Eastern Students Association",
        "description": "A community for students from Arab countries, Iran, Turkey, and the broader Middle East region. Cultural events, Arabic calligraphy workshops, food nights, and support for navigating life in Korea.",
        "category": "National Community",
        "university": "JBNU",
        "club_type": "community",
        "meeting_time": "Every Thursday 6:00 PM",
        "location": "International House, Room 106",
        "country": None,
    },
]


def seed():
    from models import User
    with app.app_context():
        # Find the admin user
        admin = User.query.filter_by(email="jaloliddinqulmatov12@gmail.com").first()
        if not admin:
            print("❌ Admin user not found. Register first on the live site, then run make_admin.py")
            sys.exit(1)

        print(f"👤 Found user: {admin.name} (id={admin.id}) — setting as creator of all content")

        added_jobs = 0
        for j in JOBS:
            exists = Job.query.filter_by(title=j["title"], company=j["company"]).first()
            if not exists:
                db.session.add(Job(**j, created_by=admin.id))
                added_jobs += 1

        added_clubs = 0
        for c in CLUBS:
            exists = Club.query.filter_by(name=c["name"], university=c.get("university", "JBNU")).first()
            if not exists:
                db.session.add(Club(**c, created_by=admin.id))
                added_clubs += 1

        db.session.commit()
        print(f"✅ Added {added_jobs} internships and {added_clubs} clubs/communities.")
        print(f"   You are the creator — you can edit and delete all of them.")


if __name__ == "__main__":
    seed()
